# Data parameters
experiment_name: 'vgg'
dataset_name: mvtec
last_checkpoint: 300


# Training parameters
num_epochs: 301
batch_size: 64
learning_rate: 1e-3
mvtec_img_size: 128

normal_class: 'metal_nut' # mvtec:'metal_nut'

lamda: 0.1


pretrain: True # True:use pre-trained vgg as source network --- False:use random initialize
use_bias: False # True:using bias term in neural network layer
equal_network_size: False # True:using equal network size for cloner and source network --- False:smaller network for cloner
direction_loss_only: False
continue_train: False


# Test parameters
localization_test: True # True:For Localization Test --- False:For Detection
localization_method: 'gbp' # gradients , smooth_grad , gbp



